-- The pluggable database used is XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;

-- Drop the users
DROP USER SALES CASCADE;
DROP USER ELECTRONICA_SELLER CASCADE;
DROP USER MAX_SELLER CASCADE;
DROP USER PANAMERICA_SELLER CASCADE;

-- Create the users
CREATE USER SALES IDENTIFIED BY adminsales;
ALTER USER SALES DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER SALES TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO SALES;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO SALES;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO SALES;

CREATE USER ELECTRONICA_SELLER IDENTIFIED BY ELECTRONICA_SELLER_ADMIN_SALES;
ALTER USER ELECTRONICA_SELLER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER ELECTRONICA_SELLER TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO ELECTRONICA_SELLER;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO ELECTRONICA_SELLER;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO ELECTRONICA_SELLER;

CREATE USER MAX_SELLER IDENTIFIED BY MAX_SELLER_ADMIN_SALES;
ALTER USER MAX_SELLER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER MAX_SELLER TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO MAX_SELLER;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO MAX_SELLER;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO MAX_SELLER;

CREATE USER PANAMERICA_SELLER IDENTIFIED BY PANAMERICA_SELLER_ADMIN_SALES;
ALTER USER PANAMERICA_SELLER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER PANAMERICA_SELLER TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO PANAMERICA_SELLER;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO PANAMERICA_SELLER;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO PANAMERICA_SELLER;

--------------------------------------------------------
--  File created - Monday-March-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CLIENTES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SALES"."CLIENTES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CREDENCIALES_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SALES"."CREDENCIALES_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence VENDEDORES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SALES"."VENDEDORES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "SALES"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"NIT" NUMBER(*,0), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"TELEFONO" VARCHAR2(8 CHAR), 
	"TIPO_CLIENTE" VARCHAR2(20 BYTE), 
	"TIENE_SUSCRIPCION" VARCHAR2(5 CHAR), 
	"VENCIMIENTO_SUSCRIPCION" DATE, 
	"PATENTE_COMERCIO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PATENTE_COMERCIO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "SALES"."CLIENTES" TO "MAX_SELLER";
  GRANT REFERENCES ON "SALES"."CLIENTES" TO "MAX_SELLER";
  GRANT SELECT ON "SALES"."CLIENTES" TO "ELECTRONICA_SELLER";
  GRANT REFERENCES ON "SALES"."CLIENTES" TO "ELECTRONICA_SELLER";
  GRANT SELECT ON "SALES"."CLIENTES" TO "PANAMERICA_SELLER";
  GRANT REFERENCES ON "SALES"."CLIENTES" TO "PANAMERICA_SELLER";
  GRANT SELECT ON "SALES"."CLIENTES" TO "PQWO_SELLER";
  GRANT REFERENCES ON "SALES"."CLIENTES" TO "PQWO_SELLER";
--------------------------------------------------------
--  DDL for Table CREDENCIALES_USUARIOS
--------------------------------------------------------

  CREATE TABLE "SALES"."CREDENCIALES_USUARIOS" 
   (	"ID_CREDENCIAL" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"TIPO_USUARIO" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"SALT" VARCHAR2(32 CHAR), 
	"HASH" VARCHAR2(64 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARCAS
--------------------------------------------------------

  CREATE TABLE "SALES"."MARCAS" 
   (	"ID_MARCA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "SALES"."MARCAS" TO "MAX_SELLER";
  GRANT REFERENCES ON "SALES"."MARCAS" TO "MAX_SELLER";
  GRANT SELECT ON "SALES"."MARCAS" TO "ELECTRONICA_SELLER";
  GRANT REFERENCES ON "SALES"."MARCAS" TO "ELECTRONICA_SELLER";
  GRANT SELECT ON "SALES"."MARCAS" TO "PANAMERICA_SELLER";
  GRANT REFERENCES ON "SALES"."MARCAS" TO "PANAMERICA_SELLER";
  GRANT SELECT ON "SALES"."MARCAS" TO "PQWO_SELLER";
  GRANT REFERENCES ON "SALES"."MARCAS" TO "PQWO_SELLER";
--------------------------------------------------------
--  DDL for Table VENDEDORES
--------------------------------------------------------

  CREATE TABLE "SALES"."VENDEDORES" 
   (	"ID_VENDEDOR" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "SALES"."VENDEDORES" TO "MAX_SELLER";
  GRANT REFERENCES ON "SALES"."VENDEDORES" TO "MAX_SELLER";
  GRANT SELECT ON "SALES"."VENDEDORES" TO "ELECTRONICA_SELLER";
  GRANT REFERENCES ON "SALES"."VENDEDORES" TO "ELECTRONICA_SELLER";
  GRANT SELECT ON "SALES"."VENDEDORES" TO "PANAMERICA_SELLER";
  GRANT REFERENCES ON "SALES"."VENDEDORES" TO "PANAMERICA_SELLER";
  GRANT SELECT ON "SALES"."VENDEDORES" TO "PQWO_SELLER";
  GRANT REFERENCES ON "SALES"."VENDEDORES" TO "PQWO_SELLER";
REM INSERTING into SALES.CLIENTES
SET DEFINE OFF;
Insert into SALES.CLIENTES (ID_CLIENTE,NOMBRE,NIT,EMAIL,TELEFONO,TIPO_CLIENTE,TIENE_SUSCRIPCION,VENCIMIENTO_SUSCRIPCION) values (1,'Juan Gutierrez',null,null,null,'individual','False',null);
REM INSERTING into SALES.CREDENCIALES_USUARIOS
SET DEFINE OFF;
Insert into SALES.CREDENCIALES_USUARIOS (ID_CREDENCIAL,ID_CLIENTE,ID_VENDEDOR,TIPO_USUARIO,EMAIL,SALT,HASH) values (4,1,null,'cliente','juan.gutierrez@gmail.com','Ag2axQennmH7XIr2CYqoYb9slQyGgLZt','01b25683db46c9bdd77e69121ce01bce30ceef72f58413e7734298179f0d45ed');
Insert into SALES.CREDENCIALES_USUARIOS (ID_CREDENCIAL,ID_CLIENTE,ID_VENDEDOR,TIPO_USUARIO,EMAIL,SALT,HASH) values (1,null,null,'vendedor','max@electronicos.com','wDLfjw3J9NzxrLePXWobwpwZ8WG0g338','09b4508e51d860825dca119d2a0cf087554dbc2a554c98c3932a0eefded1a274');
Insert into SALES.CREDENCIALES_USUARIOS (ID_CREDENCIAL,ID_CLIENTE,ID_VENDEDOR,TIPO_USUARIO,EMAIL,SALT,HASH) values (3,null,null,'vendedor','panamerica@electonicos.com','TVtTykdm6rV3zjwa1NUsPOpadxKbwkv9','a6a901316995ec5c89116ca0bdc0d2c8eabe35023eb880669e1d29382bdf7749');
Insert into SALES.CREDENCIALES_USUARIOS (ID_CREDENCIAL,ID_CLIENTE,ID_VENDEDOR,TIPO_USUARIO,EMAIL,SALT,HASH) values (2,null,null,'vendedor','electronica@tienda.com','mvghFfwN5zRSnL24z484Cv4aSXSb57eb','c058937a75a4e6a20dc0361017bec9ce7b80dc1729a968af2c3d3e2b22d03d72');
REM INSERTING into SALES.MARCAS
SET DEFINE OFF;
Insert into SALES.MARCAS (ID_MARCA,NOMBRE) values (1,'Samsung');
Insert into SALES.MARCAS (ID_MARCA,NOMBRE) values (2,'Asus');
Insert into SALES.MARCAS (ID_MARCA,NOMBRE) values (3,'Bose');
Insert into SALES.MARCAS (ID_MARCA,NOMBRE) values (4,'Dell');
Insert into SALES.MARCAS (ID_MARCA,NOMBRE) values (5,'Acer');
REM INSERTING into SALES.VENDEDORES
SET DEFINE OFF;
Insert into SALES.VENDEDORES (ID_VENDEDOR,NOMBRE) values (3,'Panamerica');
Insert into SALES.VENDEDORES (ID_VENDEDOR,NOMBRE) values (2,'Electronica');
Insert into SALES.VENDEDORES (ID_VENDEDOR,NOMBRE) values (1,'MAX');
--------------------------------------------------------
--  DDL for Index CREDENCIALES_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALES"."CREDENCIALES_USUARIO_PK" ON "SALES"."CREDENCIALES_USUARIOS" ("ID_CREDENCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENDEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALES"."VENDEDORES_PK" ON "SALES"."VENDEDORES" ("ID_VENDEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARCAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALES"."MARCAS_PK" ON "SALES"."MARCAS" ("ID_MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALES"."CLIENTES_PK" ON "SALES"."CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CREDENCIALES_USUARIO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALES"."CREDENCIALES_USUARIO_UK1" ON "SALES"."CREDENCIALES_USUARIOS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CLIENTES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SALES"."CLIENTES_TRG" 
BEFORE INSERT ON CLIENTES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SALES"."CLIENTES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREDENCIALES_USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SALES"."CREDENCIALES_USUARIO_TRG" 
BEFORE INSERT ON "CREDENCIALES_USUARIOS" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SALES"."CREDENCIALES_USUARIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VENDEDORES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SALES"."VENDEDORES_TRG" 
BEFORE INSERT ON VENDEDORES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_VENDEDOR IS NULL THEN
      SELECT VENDEDORES_SEQ.NEXTVAL INTO :NEW.ID_VENDEDOR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SALES"."VENDEDORES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table VENDEDORES
--------------------------------------------------------

  ALTER TABLE "SALES"."VENDEDORES" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "SALES"."VENDEDORES" ADD CONSTRAINT "VENDEDORES_PK" PRIMARY KEY ("ID_VENDEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CREDENCIALES_USUARIOS
--------------------------------------------------------

  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" MODIFY ("ID_CREDENCIAL" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" ADD CONSTRAINT "CREDENCIALES_USUARIO_PK" PRIMARY KEY ("ID_CREDENCIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" ADD CONSTRAINT "CREDENCIALES_USUARIO_IDENTITY_CHK" CHECK (TIPO_USUARIO IN ('vendedor', 'cliente')) ENABLE;
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" MODIFY ("TIPO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" MODIFY ("SALT" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" MODIFY ("HASH" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" ADD CONSTRAINT "CREDENCIALES_USUARIO_UNIQUE_EMAIL" UNIQUE ("EMAIL")
  USING INDEX (CREATE UNIQUE INDEX "SALES"."CREDENCIALES_USUARIO_UK1" ON "SALES"."CREDENCIALES_USUARIOS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "SALES"."CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CLIENTES" MODIFY ("TIENE_SUSCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SALES"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SALES"."CLIENTES" ADD CONSTRAINT "CLIENTES_CHK1" CHECK (TIPO_CLIENTE IN ('individual', 'grande', 'distribuidor')) ENABLE;
  ALTER TABLE "SALES"."CLIENTES" ADD CONSTRAINT "CLIENTES_CHK2" CHECK (TIENE_SUSCRIPCION IN ('True', 'False')) ENABLE;
--------------------------------------------------------
--  Constraints for Table MARCAS
--------------------------------------------------------

  ALTER TABLE "SALES"."MARCAS" MODIFY ("ID_MARCA" NOT NULL ENABLE);
  ALTER TABLE "SALES"."MARCAS" ADD CONSTRAINT "MARCAS_PK" PRIMARY KEY ("ID_MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CREDENCIALES_USUARIOS
--------------------------------------------------------

  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" ADD CONSTRAINT "CREDENCIALES_USUARIO_CLIENTS_FK" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "SALES"."CREDENCIALES_USUARIOS" ADD CONSTRAINT "CREDENCIALES_USUARIO_SELLERS_FK" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;

--------------------------------------------------------
--  File created - Monday-March-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" 
   (	"ID_DISPOSITIVO" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"ID_MARCA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"EXISTENCIAS" NUMBER(*,0), 
	"PRECIO" FLOAT(126), 
	"CODIGO_MODELO" VARCHAR2(100 BYTE), 
	"COLOR" VARCHAR2(100 BYTE), 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"TIEMPO_GARANTIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."DISPOSITIVOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" 
   (	"ID_DISPOSITIVO_X_PEDIDO" NUMBER(*,0), 
	"ID_PEDIDO" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" TO "SALES";
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" 
   (	"ID_DISPOSITIVO_X_VENTA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" TO "SALES";
--------------------------------------------------------
--  DDL for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" 
   (	"ID_FOTO" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"FOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FOTO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."PAGOS" 
   (	"ID_PAGO" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"FECHA_PAGO" DATE, 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."PAGOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" 
   (	"ID_PEDIDO" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"FECHA_PEDIDO" DATE, 
	"PRECIO_PEDIDO" FLOAT(126), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0), 
	"IMPUESTOS" FLOAT(126), 
	"DESCUENTOS" FLOAT(126), 
	"TOTAL_PEDIDO" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" TO "SALES";
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "ELECTRONICA_SELLER"."VENTAS" 
   (	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"FECHA_VENTA" DATE, 
	"PRECIO_VENTA" FLOAT(126), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0), 
	"IMPUESTOS" FLOAT(126), 
	"DESCUENTOS" FLOAT(126), 
	"TOTAL_VENTA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ELECTRONICA_SELLER"."VENTAS" TO "SALES";
REM INSERTING into ELECTRONICA_SELLER.DISPOSITIVOS
SET DEFINE OFF;
Insert into ELECTRONICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (1,2,1,'laptop abc 123','abc esto es una descripcion.',328,6500,'ab525','negro','eletrodomesticos',1);
Insert into ELECTRONICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (3,2,1,'Super Laptop','abc esto es una descripcion.',179,6500,'ab525','negro','eletrodomesticos',1);
Insert into ELECTRONICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (4,2,1,'Telefono Inteligente','El mejor telefono que jamas hayas utilizado',337,5000,'TEL-INTEL','blanco','Electrodomesticos',2);
Insert into ELECTRONICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (2,2,1,'Mega Laptop','abc esto es una descripcion.',500,6500,'ab525','negro','eletrodomesticos',1);
REM INSERTING into ELECTRONICA_SELLER.DISPOSITIVOS_X_PEDIDOS_FUTUROS
SET DEFINE OFF;
REM INSERTING into ELECTRONICA_SELLER.DISPOSITIVOS_X_VENTAS
SET DEFINE OFF;
REM INSERTING into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS
SET DEFINE OFF;
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (1,1);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (2,1);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (3,1);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (4,2);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (5,2);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (6,2);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (7,3);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (8,3);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (9,3);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (10,4);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (11,4);
Insert into ELECTRONICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (12,4);
REM INSERTING into ELECTRONICA_SELLER.PAGOS
SET DEFINE OFF;
REM INSERTING into ELECTRONICA_SELLER.PEDIDOS_FUTUROS
SET DEFINE OFF;
REM INSERTING into ELECTRONICA_SELLER.VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("FECHA_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("PRECIO_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("DESCUENTOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("TOTAL_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" ADD PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_DISPOSITIVO_X_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD PRIMARY KEY ("ID_DISPOSITIVO_X_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("ID_MARCA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("EXISTENCIAS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("CODIGO_MODELO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" MODIFY ("TIEMPO_GARANTIA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" ADD PRIMARY KEY ("ID_DISPOSITIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" MODIFY ("ID_PAGO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" MODIFY ("FECHA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" ADD PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_DISPOSITIVO_X_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" ADD PRIMARY KEY ("ID_DISPOSITIVO_X_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("FOTO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" ADD PRIMARY KEY ("ID_FOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("ID_FOTO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("FECHA_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("PRECIO_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("DESCUENTOS" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" MODIFY ("TOTAL_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" ADD CONSTRAINT "FK_MARCAS_DISPOSITIVOS" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "SALES"."MARCAS" ("ID_MARCA") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS" ADD CONSTRAINT "FK_VENDEDORES" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_DISPOSITIVOS_X_PEDIDOS_FUTUROS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "ELECTRONICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_PEDIDOS_FUTUROS_X_PEDIDOS_FUTUROS" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" ("ID_PEDIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" ADD CONSTRAINT "FK_DISPOSITIVOS_X_VENTAS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "ELECTRONICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."DISPOSITIVOS_X_VENTAS" ADD CONSTRAINT "FK_VENTAS_X_VENTAS" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "ELECTRONICA_SELLER"."VENTAS" ("ID_VENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."FOTOS_DISPOSITIVOS" ADD CONSTRAINT "FK_FOTOS_DISPOSITIVOS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "ELECTRONICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" ADD CONSTRAINT "FK_VENTAS_PAGOS" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "ELECTRONICA_SELLER"."VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" ADD CONSTRAINT "FK_CLIENTES_PAGOS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."PAGOS" ADD CONSTRAINT "FK_VENDEDORES_PAGOS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_CLIENTES_PEDIDOS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_VENDEDORES_PEDIDOS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" ADD CONSTRAINT "FK_CLIENTES_VENTAS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" ADD CONSTRAINT "FK_VENDEDORES_VENTAS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
  ALTER TABLE "ELECTRONICA_SELLER"."VENTAS" ADD CONSTRAINT "FK_DISPOSITIVOS_VENTAS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "ELECTRONICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;

--------------------------------------------------------
--  File created - Monday-March-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."DISPOSITIVOS" 
   (	"ID_DISPOSITIVO" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"ID_MARCA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"EXISTENCIAS" NUMBER(*,0), 
	"PRECIO" FLOAT(126), 
	"CODIGO_MODELO" VARCHAR2(100 BYTE), 
	"COLOR" VARCHAR2(100 BYTE), 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"TIEMPO_GARANTIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "MAX_SELLER"."DISPOSITIVOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" 
   (	"ID_DISPOSITIVO_X_PEDIDO" NUMBER(*,0), 
	"ID_PEDIDO" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" TO "SALES";
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" 
   (	"ID_DISPOSITIVO_X_VENTA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" TO "SALES";
--------------------------------------------------------
--  DDL for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."FOTOS_DISPOSITIVOS" 
   (	"ID_FOTO" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"FOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FOTO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "MAX_SELLER"."FOTOS_DISPOSITIVOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."PAGOS" 
   (	"ID_PAGO" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"FECHA_PAGO" DATE, 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "MAX_SELLER"."PAGOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" 
   (	"ID_PEDIDO" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"FECHA_PEDIDO" DATE, 
	"PRECIO_PEDIDO" FLOAT(126), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0), 
	"IMPUESTOS" FLOAT(126), 
	"DESCUENTOS" FLOAT(126), 
	"TOTAL_PEDIDO" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "MAX_SELLER"."PEDIDOS_FUTUROS" TO "SALES";
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "MAX_SELLER"."VENTAS" 
   (	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"FECHA_VENTA" DATE, 
	"PRECIO_VENTA" FLOAT(126), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0), 
	"IMPUESTOS" FLOAT(126), 
	"DESCUENTOS" FLOAT(126), 
	"TOTAL_VENTA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "MAX_SELLER"."VENTAS" TO "SALES";
REM INSERTING into MAX_SELLER.DISPOSITIVOS
SET DEFINE OFF;
Insert into MAX_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (1,1,1,'Laptop T28','Laptop de gran utilidad',123,7250.75,'LPT028','negro','Eletrodomesticos',1);
Insert into MAX_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (3,1,1,'Laptop X25','Laptop para todas tus necesidades',443,6725.5,'LPTX25','negro','Eletrodomesticos',1);
Insert into MAX_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (5,1,1,'Telefono Inteligente RPX28','Un buen telefono inteligente para todos los usos',478,4350,'TIRPX28','gris','Electrodomesticos',2);
Insert into MAX_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (2,1,1,'Laptop r2487','Laptop gaming',193,6555.75,'LPTR2487','negro','Eletrodomesticos',3);
Insert into MAX_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (4,1,1,'Telefono Inteligente A37','Un gran telefono inteligente',325,4250,'TIA37','blanco','Electrodomesticos',2);
REM INSERTING into MAX_SELLER.DISPOSITIVOS_X_PEDIDOS_FUTUROS
SET DEFINE OFF;
REM INSERTING into MAX_SELLER.DISPOSITIVOS_X_VENTAS
SET DEFINE OFF;
REM INSERTING into MAX_SELLER.FOTOS_DISPOSITIVOS
SET DEFINE OFF;
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (1,1);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (2,1);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (3,1);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (4,2);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (5,2);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (6,2);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (7,3);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (8,3);
Insert into MAX_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (9,3);
REM INSERTING into MAX_SELLER.PAGOS
SET DEFINE OFF;
REM INSERTING into MAX_SELLER.PEDIDOS_FUTUROS
SET DEFINE OFF;
REM INSERTING into MAX_SELLER.VENTAS
SET DEFINE OFF;
Insert into MAX_SELLER.VENTAS (ID_VENTA,ID_CLIENTE,ID_VENDEDOR,ID_DISPOSITIVO,FECHA_VENTA,PRECIO_VENTA,CANTIDAD_DISPOSITIVOS,IMPUESTOS,DESCUENTOS,TOTAL_VENTA) values (1,1,1,1,to_date('14-MAR-22','DD-MON-RR'),253650,20,40050,0,253650);
Insert into MAX_SELLER.VENTAS (ID_VENTA,ID_CLIENTE,ID_VENDEDOR,ID_DISPOSITIVO,FECHA_VENTA,PRECIO_VENTA,CANTIDAD_DISPOSITIVOS,IMPUESTOS,DESCUENTOS,TOTAL_VENTA) values (2,1,1,2,to_date('14-MAR-22','DD-MON-RR'),4048175.625,325,639185.625,0,4048175.625);
Insert into MAX_SELLER.VENTAS (ID_VENTA,ID_CLIENTE,ID_VENDEDOR,ID_DISPOSITIVO,FECHA_VENTA,PRECIO_VENTA,CANTIDAD_DISPOSITIVOS,IMPUESTOS,DESCUENTOS,TOTAL_VENTA) values (3,1,1,4,to_date('14-MAR-22','DD-MON-RR'),37525,3,5925,0,37525);
--------------------------------------------------------
--  Constraints for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("FECHA_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("PRECIO_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("DESCUENTOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" MODIFY ("TOTAL_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" ADD PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("ID_MARCA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("EXISTENCIAS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("CODIGO_MODELO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" MODIFY ("TIEMPO_GARANTIA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" ADD PRIMARY KEY ("ID_DISPOSITIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("FECHA_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("PRECIO_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("DESCUENTOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" MODIFY ("TOTAL_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."VENTAS" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_DISPOSITIVO_X_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" ADD PRIMARY KEY ("ID_DISPOSITIVO_X_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("ID_FOTO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("FOTO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."FOTOS_DISPOSITIVOS" ADD PRIMARY KEY ("ID_FOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_DISPOSITIVO_X_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD PRIMARY KEY ("ID_DISPOSITIVO_X_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."PAGOS" MODIFY ("ID_PAGO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PAGOS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PAGOS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PAGOS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PAGOS" MODIFY ("FECHA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PAGOS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "MAX_SELLER"."PAGOS" ADD PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" ADD CONSTRAINT "FK_MARCAS_DISPOSITIVOS" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "SALES"."MARCAS" ("ID_MARCA") ENABLE;
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS" ADD CONSTRAINT "FK_VENDEDORES" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_DISPOSITIVOS_X_PEDIDOS_FUTUROS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "MAX_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_PEDIDOS_FUTUROS_X_PEDIDOS_FUTUROS" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "MAX_SELLER"."PEDIDOS_FUTUROS" ("ID_PEDIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" ADD CONSTRAINT "FK_DISPOSITIVOS_X_VENTAS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "MAX_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
  ALTER TABLE "MAX_SELLER"."DISPOSITIVOS_X_VENTAS" ADD CONSTRAINT "FK_VENTAS_X_VENTAS" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "MAX_SELLER"."VENTAS" ("ID_VENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."FOTOS_DISPOSITIVOS" ADD CONSTRAINT "FK_FOTOS_DISPOSITIVOS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "MAX_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."PAGOS" ADD CONSTRAINT "FK_VENTAS_PAGOS" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "MAX_SELLER"."VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "MAX_SELLER"."PAGOS" ADD CONSTRAINT "FK_CLIENTES_PAGOS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "MAX_SELLER"."PAGOS" ADD CONSTRAINT "FK_VENDEDORES_PAGOS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_CLIENTES_PEDIDOS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "MAX_SELLER"."PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_VENDEDORES_PEDIDOS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "MAX_SELLER"."VENTAS" ADD CONSTRAINT "FK_CLIENTES_VENTAS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "MAX_SELLER"."VENTAS" ADD CONSTRAINT "FK_VENDEDORES_VENTAS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
  ALTER TABLE "MAX_SELLER"."VENTAS" ADD CONSTRAINT "FK_DISPOSITIVOS_VENTAS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "MAX_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;

--------------------------------------------------------
--  File created - Monday-March-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" 
   (	"ID_DISPOSITIVO" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"ID_MARCA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"EXISTENCIAS" NUMBER(*,0), 
	"PRECIO" FLOAT(126), 
	"CODIGO_MODELO" VARCHAR2(100 BYTE), 
	"COLOR" VARCHAR2(100 BYTE), 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"TIEMPO_GARANTIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "PANAMERICA_SELLER"."DISPOSITIVOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" 
   (	"ID_DISPOSITIVO_X_PEDIDO" NUMBER(*,0), 
	"ID_PEDIDO" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" TO "SALES";
--------------------------------------------------------
--  DDL for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" 
   (	"ID_DISPOSITIVO_X_VENTA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" TO "SALES";
--------------------------------------------------------
--  DDL for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" 
   (	"ID_FOTO" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"FOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FOTO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."PAGOS" 
   (	"ID_PAGO" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"FECHA_PAGO" DATE, 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "PANAMERICA_SELLER"."PAGOS" TO "SALES";
--------------------------------------------------------
--  DDL for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" 
   (	"ID_PEDIDO" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"FECHA_PEDIDO" DATE, 
	"PRECIO_PEDIDO" FLOAT(126), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0), 
	"IMPUESTOS" FLOAT(126), 
	"DESCUENTOS" FLOAT(126), 
	"TOTAL_PEDIDO" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" TO "SALES";
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "PANAMERICA_SELLER"."VENTAS" 
   (	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_VENDEDOR" NUMBER(*,0), 
	"ID_DISPOSITIVO" NUMBER(*,0), 
	"FECHA_VENTA" DATE, 
	"PRECIO_VENTA" FLOAT(126), 
	"CANTIDAD_DISPOSITIVOS" NUMBER(*,0), 
	"IMPUESTOS" FLOAT(126), 
	"DESCUENTOS" FLOAT(126), 
	"TOTAL_VENTA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "PANAMERICA_SELLER"."VENTAS" TO "SALES";
REM INSERTING into PANAMERICA_SELLER.DISPOSITIVOS
SET DEFINE OFF;
Insert into PANAMERICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (2,3,1,'Super Duper Laptop','Una gran laptop',723,7000,'ab525','Negro','Eletrodomesticos',1);
Insert into PANAMERICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (3,3,1,'Megar Laptop','abc esto es una descripcion.',392,7000,'ab525','negro','eletrodomesticos',1);
Insert into PANAMERICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (5,3,1,'MBPD Laptop','abc esto es una descripcion.',500,7000,'ab525','negro','eletrodomesticos',1);
Insert into PANAMERICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (1,3,1,'Laptop','ABC esto es una descripciÃÂ³n.',155,7000,'ab525','Negro','Eletrodomesticos',1);
Insert into PANAMERICA_SELLER.DISPOSITIVOS (ID_DISPOSITIVO,ID_VENDEDOR,ID_MARCA,NOMBRE,DESCRIPCION,EXISTENCIAS,PRECIO,CODIGO_MODELO,COLOR,CATEGORIA,TIEMPO_GARANTIA) values (4,3,1,'Tnpo Laptop AP15','La mejor laptop del mercado',317,7275.18,'LPTTNPAP15','Negro','Electrodomesticos',2);
REM INSERTING into PANAMERICA_SELLER.DISPOSITIVOS_X_PEDIDOS_FUTUROS
SET DEFINE OFF;
REM INSERTING into PANAMERICA_SELLER.DISPOSITIVOS_X_VENTAS
SET DEFINE OFF;
REM INSERTING into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS
SET DEFINE OFF;
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (1,1);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (2,1);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (3,1);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (4,2);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (5,2);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (6,2);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (7,3);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (8,3);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (9,3);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (10,4);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (11,4);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (12,4);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (13,5);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (14,5);
Insert into PANAMERICA_SELLER.FOTOS_DISPOSITIVOS (ID_FOTO,ID_DISPOSITIVO) values (15,5);
REM INSERTING into PANAMERICA_SELLER.PAGOS
SET DEFINE OFF;
REM INSERTING into PANAMERICA_SELLER.PEDIDOS_FUTUROS
SET DEFINE OFF;
REM INSERTING into PANAMERICA_SELLER.VENTAS
SET DEFINE OFF;
Insert into PANAMERICA_SELLER.VENTAS (ID_VENTA,ID_CLIENTE,ID_VENDEDOR,ID_DISPOSITIVO,FECHA_VENTA,PRECIO_VENTA,CANTIDAD_DISPOSITIVOS,IMPUESTOS,DESCUENTOS,TOTAL_VENTA) values (2,1,3,3,to_date('14-MAR-22','DD-MON-RR'),37525,1,5925,0,37525);
Insert into PANAMERICA_SELLER.VENTAS (ID_VENTA,ID_CLIENTE,ID_VENDEDOR,ID_DISPOSITIVO,FECHA_VENTA,PRECIO_VENTA,CANTIDAD_DISPOSITIVOS,IMPUESTOS,DESCUENTOS,TOTAL_VENTA) values (1,1,3,3,to_date('14-MAR-22','DD-MON-RR'),1755600,132,277200,0,1755600);
--------------------------------------------------------
--  Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("FECHA_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("PRECIO_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("DESCUENTOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" MODIFY ("TOTAL_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_DISPOSITIVO_X_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" ADD PRIMARY KEY ("ID_DISPOSITIVO_X_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_DISPOSITIVO_X_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD PRIMARY KEY ("ID_DISPOSITIVO_X_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("FECHA_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("PRECIO_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("CANTIDAD_DISPOSITIVOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("DESCUENTOS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("TOTAL_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" ADD PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("ID_FOTO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" MODIFY ("FOTO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" ADD PRIMARY KEY ("ID_FOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" MODIFY ("ID_PAGO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" MODIFY ("FECHA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" ADD PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("ID_VENDEDOR" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("ID_MARCA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("EXISTENCIAS" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("CODIGO_MODELO" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" MODIFY ("TIEMPO_GARANTIA" NOT NULL ENABLE);
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" ADD PRIMARY KEY ("ID_DISPOSITIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" ADD CONSTRAINT "FK_MARCAS_DISPOSITIVOS" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "SALES"."MARCAS" ("ID_MARCA") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS" ADD CONSTRAINT "FK_VENDEDORES" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS_X_PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_DISPOSITIVOS_X_PEDIDOS_FUTUROS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "PANAMERICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_PEDIDOS_FUTUROS_X_PEDIDOS_FUTUROS" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" ("ID_PEDIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPOSITIVOS_X_VENTAS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" ADD CONSTRAINT "FK_DISPOSITIVOS_X_VENTAS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "PANAMERICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."DISPOSITIVOS_X_VENTAS" ADD CONSTRAINT "FK_VENTAS_X_VENTAS" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "PANAMERICA_SELLER"."VENTAS" ("ID_VENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOTOS_DISPOSITIVOS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."FOTOS_DISPOSITIVOS" ADD CONSTRAINT "FK_FOTOS_DISPOSITIVOS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "PANAMERICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" ADD CONSTRAINT "FK_VENTAS_PAGOS" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "PANAMERICA_SELLER"."VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" ADD CONSTRAINT "FK_CLIENTES_PAGOS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."PAGOS" ADD CONSTRAINT "FK_VENDEDORES_PAGOS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS_FUTUROS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_CLIENTES_PEDIDOS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."PEDIDOS_FUTUROS" ADD CONSTRAINT "FK_VENDEDORES_PEDIDOS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" ADD CONSTRAINT "FK_CLIENTES_VENTAS" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SALES"."CLIENTES" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" ADD CONSTRAINT "FK_VENDEDORES_VENTAS" FOREIGN KEY ("ID_VENDEDOR")
	  REFERENCES "SALES"."VENDEDORES" ("ID_VENDEDOR") ENABLE;
  ALTER TABLE "PANAMERICA_SELLER"."VENTAS" ADD CONSTRAINT "FK_DISPOSITIVOS_VENTAS" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "PANAMERICA_SELLER"."DISPOSITIVOS" ("ID_DISPOSITIVO") ENABLE;
